apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  namespace: default
  labels:
    env: test
    app: main
    tiers: frontend
    owner: VStupa
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5%
      maxUnavailable: 5%
  template:
    metadata:
      labels:
        app: myapp # Service(Proxy) will look for those Pods labels
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: nginx-port
        - name: multitool
          imagePullPolicy: IfNotPresent
          image: praqma/network-multitool:minimal
          env:
            - name: "HTTP_PORT"
              value: "8080"
          # ports:
          #   - containerPort: 8080
          #     name: multitool-port
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp # Select pods with those labels
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80 # Port on proxy
      targetPort: nginx-port # Port on pods
    - name: multitool-http
      protocol: TCP
      port: 8080
      targetPort: 8080 #multitool-port
  #type: NodePort
  #type: ClusterIP
  #type: LoadBalancer
