---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp # Select pods with those labels
  ports:
    - name: app-listner
      protocol: TCP
      port: 80 # Port on proxy
      targetPort: 80 # Port on pods
  type: NodePort
