{
 "title": "Sys",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[10m])) by (instance)) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes ", "legendFormat": "total" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "available" }
   ]
  },
  {
   "title": "Disk Spaces",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_avail_bytes{fstype!='tmpfs'} / node_filesystem_size_bytes * 100"
    }
   ]
  }
 ]
}