apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      #image: busybox:1.28
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
  restartPolicy: OnFailure
  # The pod template ends here
