apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: netology-web
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: netology-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: netology-service
      protocol: TCP
      port: 80
      targetPort: http-web-svc
